# Reshaping Arrays

In [1]:
import numpy as np

In [15]:
arr=np.arange(9)
print(arr)
#1D array to 2D
reshaped=arr.reshape(3,3)
print(reshaped)
# Flatten an array
A=reshaped.flatten()
print(A)
B=arr.reshape(3,-1)
print(B)
C=B.ravel()
print('C',C)
print(B)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
C [0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
#Transposee
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A)
print(A.transpose())
print(A.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [25]:
#reshape() dans les modèles IA (exemple pour les images)
img=np.random.rand(28,28) #784 elements
print(img)
#vecteur 1D 
imgflatened=img.reshape(-1)
print('\n\n\n1D imag :',imgflatened)

[[3.70294246e-01 9.74128654e-01 3.89018455e-01 2.65965758e-01
  7.95235499e-01 6.92678782e-01 2.23391552e-01 6.81497359e-01
  9.85439514e-01 7.10259083e-01 8.87070627e-01 5.45474670e-02
  3.43248052e-01 2.10276404e-01 8.87276173e-01 2.79989998e-01
  4.43538450e-01 2.47428747e-01 5.07874835e-01 7.79773246e-01
  3.03719282e-01 7.31206693e-01 7.57331524e-01 4.59051831e-01
  4.95934957e-01 4.91265456e-01 2.66149763e-02 4.97078889e-01]
 [4.35655313e-02 3.17179124e-01 1.98467206e-01 3.29718094e-01
  6.66509558e-01 9.43836792e-01 8.97138228e-01 9.41006096e-01
  1.83561297e-01 9.82200379e-01 5.73853811e-01 9.43149151e-01
  3.33573036e-01 3.03627813e-02 7.37283055e-01 9.89389347e-01
  5.87090111e-01 2.95622820e-01 1.03372397e-01 6.40177295e-01
  4.71459286e-01 4.91317036e-01 7.35092593e-01 8.66768042e-01
  2.92145251e-01 4.42106138e-02 8.24953145e-01 5.80061502e-01]
 [8.86748967e-01 9.33326257e-01 4.56655330e-01 1.70368672e-01
  6.96629981e-01 7.75890344e-01 3.25023453e-01 7.46632939e-01
  9.40

In [28]:
A=np.random.rand(100,28,28)
print(A)
B=A.reshape(100,-1)
print('\n\n\n\n\nB:',B)

[[[0.97356769 0.86017911 0.6222457  ... 0.10323982 0.6904449  0.67250144]
  [0.49098083 0.23242654 0.50288707 ... 0.6622909  0.68582755 0.99681062]
  [0.58462354 0.820492   0.36886769 ... 0.10584129 0.12115915 0.54797104]
  ...
  [0.94654358 0.68191779 0.50475768 ... 0.94632265 0.31171629 0.11408028]
  [0.19972801 0.32383552 0.65670851 ... 0.39395942 0.12721766 0.40327562]
  [0.6473296  0.68562224 0.03263355 ... 0.66771187 0.56450785 0.56394589]]

 [[0.50868436 0.12461135 0.37442621 ... 0.36912809 0.86994891 0.03823225]
  [0.22022923 0.95164842 0.80139472 ... 0.07726271 0.7589471  0.96916022]
  [0.97958312 0.60753901 0.90761251 ... 0.94576979 0.50443636 0.87141984]
  ...
  [0.72049425 0.93255403 0.46218967 ... 0.42226072 0.33171062 0.48693063]
  [0.60674927 0.13487282 0.22508561 ... 0.88428522 0.55672924 0.50961735]
  [0.9092895  0.51537413 0.24811889 ... 0.73937091 0.70423422 0.94347479]]

 [[0.24681916 0.45312818 0.21051346 ... 0.84761372 0.98355454 0.32961653]
  [0.60664061 0.244949

In [53]:
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A)
B=A.swapaxes(0,1)
print('\n\n\n',B)
C=np.squeeze(B)
print('\n\n\n',C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]



 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [32]:
C=np.linspace(0,1,5)
print(C)

[0.   0.25 0.5  0.75 1.  ]


In [54]:
arr = np.array([
    [  # Premier bloc (3x4)
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [  # Deuxième bloc (3x4)
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print(arr)
B=arr.swapaxes(0,1)
print('\n\n\n\n',B)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]




 [[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]


In [48]:
# Add new axis
arr = np.array([1, 2, 3])
print(arr)
arr_col = arr[:, np.newaxis]                # Column vector
print(arr_col)
arr_row = arr[np.newaxis, :]                # Row vector
print(arr_row)

# Remove single-dimensional entries
squeezed = np.squeeze(arr_col)              # Back to 1D
print(squeezed)

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]
[1 2 3]


# Sorting and Shuffling


In [68]:
#Sorting
A=np.array([[1,3,2,4],[9,12,10,11],[5,6,8,7]])
print(A)
B=np.sort(A)
print(B)
np.random.shuffle(A)
print('\n\n\n\n',A)

[[ 1  3  2  4]
 [ 9 12 10 11]
 [ 5  6  8  7]]
[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]]




 [[ 9 12 10 11]
 [ 5  6  8  7]
 [ 1  3  2  4]]


In [67]:
A=np.array([3, 1, 4, 2, 5])
np.random.shuffle(A)
print(A)

[4 2 3 5 1]


In [69]:
arr = np.array([[10, 20],
                [30, 40],
                [50, 60]])

shuffled = np.random.permutation(arr)

print("Shuffled array:")
print(shuffled)

print("Original array:")
print(arr)  # Reste intact


Shuffled array:
[[10 20]
 [50 60]
 [30 40]]
Original array:
[[10 20]
 [30 40]
 [50 60]]
